### ISSUE TITLE
The connection is unstable.

### ISSUE THREAD

**Issue by doremefaso888** [nopnop2002/esp-idf-ftpServer#14] opened 2024-02-22 07:44 UTC
I am using ESP32 in AP mode to create an FTP server. When connecting with FileZilla software and transferring images, the connection gets interrupted midway.

**Comment by nopnop2002** [comment] 2024-02-22 08:39
What about STA mode?

**Comment by iamnarendrans** [comment] 2024-10-21 04:49
@nopnop2002 I'm also facing the same issue, 

In STA mode. It's working perfectly, but in AP mode the connection is getting interrupted.

Files are transferring after the forceful disconnection from FileZilla 
![image](https://github.com/user-attachments/assets/45c6816a-1314-410d-b1a9-448f3c482ce7)

After the connection established, waiting for welcome message line, none of the files are transferring, after the force disconnection, it's transferring files but not all the selected files, few files were missing.

**Comment by nopnop2002** [comment] 2024-10-21 10:15
@iamnarendrans 


What kind of logs are displayed on the FTP server side?

**Comment by nopnop2002** [comment] 2024-12-06 01:17
There is a possibility that it is not in Passive mode.
I was unable to reproduce the problem using AP mode + FileZilla, so I will close it.

![FileZilla-2](https://github.com/user-attachments/assets/290636f3-d08d-4f7e-8115-5bb6f41bf456)


![FileZilla-AP-mode](https://github.com/user-attachments/assets/86a0a5c4-05df-4131-ad90-504361360de7)

**Closed as completed by nopnop2002** 2024-12-06 01:17 UTC
